name: Development builds

concurrency:
  group: devbuilds
  cancel-in-progress: true
  
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install native dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev g++-mingw-w64-x86-64 g++-mingw-w64-i686 cmake ninja-build
    - name: Build
      run: PACKAGESUFFIX=-nightly-$GITHUB_RUN_NUMBER ./build-nuget.sh
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ./dotnet/BlurgText/bin/Release/*.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/CallumDev/index.json --skip-duplicate --no-symbols
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
