name: PR check

concurrency:
  group: prcheck

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install native dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev g++-mingw-w64-x86-64 g++-mingw-w64-i686 cmake ninja-build
    - name: Build
      run: PACKAGESUFFIX=-nightly-prcheck ./build-nuget.sh win_x86 win_x64 linux_x64 managed
  buildmac_arm:
    runs-on: macos-15
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Build
      run: PACKAGESUFFIX=-prcheck ./build-nuget.sh osx_arm64
